version: '2'
services:
  zpush: 
    image: ghcr.io/si458/zpush:2.6.4
    volumes:
      - logs:/var/log/z-push
      - config:/config
      - data:/var/lib/z-push
    restart: always
    ports:
        - 80
volumes:
  logs:
    driver: local
  config:
    driver: local
  data:
    driver: local