version: '2'
services:
  zpush: 
    image: si458/zpush:latest
    volumes:
      - logs:/var/log/z-push
      - config:/etc/z-push
      - data:/var/lib/z-push
    restart: always
    ports:
        - 80
volumes:
  logs:
    driver: local
  config:
    driver: local
  data:
    driver: local